def escape(texto):
    while texto.find("  ") != -1:
        texto = texto.replace("  "," ")
    texto = texto.replace("&lt;", "<")
    texto = texto.replace("&gt;", ">")
    texto = texto.replace("%", "%25")
    texto = texto.replace("\\", "%5C")
    texto = texto.replace("\"", "%22")
    texto = texto.replace("!", "%21")
    texto = texto.replace("@", "%40")
    texto = texto.replace("#", "%23")
    texto = texto.replace("$", "%24")
    texto = texto.replace("¨", "%C2%A8")
    texto = texto.replace("&", "%26")
    texto = texto.replace("*", "*")
    texto = texto.replace("(", "%28")
    texto = texto.replace(")", "%29")
    texto = texto.replace("_", "_")
    texto = texto.replace("+", "%2B")
    texto = texto.replace(" ", "+")
    texto = texto.replace("`", "%60")
    texto = texto.replace("{", "%7B")
    texto = texto.replace("^", "%5E")
    texto = texto.replace("}", "%7D")
    texto = texto.replace("|", "%7C")
    texto = texto.replace("<", "%3C")
    texto = texto.replace(">", "%3E")
    texto = texto.replace(":", "%3A")
    texto = texto.replace("?", "%3F")
    texto = texto.replace("'", "%27")
    texto = texto.replace("¹", "%C2%B9")
    texto = texto.replace("²", "%C2%B2")
    texto = texto.replace("³", "%C2%B3")
    texto = texto.replace("£", "%C2%A3")
    texto = texto.replace("¢", "%C2%A2")
    texto = texto.replace("¬", "%C2%AC")
    texto = texto.replace("-", "-")
    texto = texto.replace("=", "%3D")
    texto = texto.replace("´", "%C2%B4")
    texto = texto.replace("[", "%5B")
    texto = texto.replace("ª", "%C2%AA")
    texto = texto.replace("~", "%7E")
    texto = texto.replace("]", "%5D")
    texto = texto.replace("º", "%C2%BA")
    texto = texto.replace(",", "%2C")
    texto = texto.replace(".", ".")
    texto = texto.replace(";", "%3B")
    texto = texto.replace("/", "%2F")
    texto = texto.replace("Ç", "%C3%87")
    texto = texto.replace("ç", "%C3%A7")
    texto = texto.replace("\n","")
    return texto



