import random


def frases(faculdade):

    if faculdade == "UNICESUMAR":
        lista = [
        "Administração 2023:\nhttps://chat.whatsapp.com/IVhBHFS4OnxDcambMWvA75",
        "Administração 2024:\nhttps://chat.whatsapp.com/LocxQMpqlGa773l0BaPwf7",
        "Agronegócio:\nhttps://chat.whatsapp.com/Dac3HZCxCOtDyWHcbZEPZm",
        "Análise e Desenvolvimento de Sistemas/Sistemas de Internet:\nhttps://chat.whatsapp.com/KlIiYnxhkxMHnKEMcSXwcO",
        "ARQUITETURA E URBANISMO\nhttps://chat.whatsapp.com/JGnfNNvYOXS8q6JqCmdlvc",
        "Automação Industrial:\nhttps://chat.whatsapp.com/FrOd3KwJh5JBAuCJ4gvLYE",
        "Biomedicina:\nhttps://chat.whatsapp.com/FbjQC82HbyiA5CWNRY9kb2",
        "Biomedicina 2024:\nhttps://chat.whatsapp.com/FPEou51VQtyFYfjh9bOuLF",
        "Ciência da Felicidade:\nhttps://chat.whatsapp.com/DEeMEjtLNMeIhEVs4AVm80",
        "Ciências Biológicas:\nhttps://chat.whatsapp.com/HixSV9ZqBMdLn5E2wKcCQ1",
        "Ciências Contábeis:\nhttps://chat.whatsapp.com/G9UNkm823jkKZhTTWXwtbo",
        "Ciências Econômicas:\nhttps://chat.whatsapp.com/GFkDHO8PxBYEcyAPm4lTV8",
        "Criminologia\nhttps://chat.whatsapp.com/Eitd9iBVt2SDS2w8xTFTyq",
        "Desing de Interiores\nhttps://chat.whatsapp.com/JkFLcRpNUamLUhHnFSal9Z",
        "Design de Moda:\nhttps://chat.whatsapp.com/DSZ8o7F3r3Z26jyhenQkB9",
        "Educação Física:\nhttps://chat.whatsapp.com/Co2qsvlqAsE7hSfSXqPSMU",
        "Enfermagem:\nhttps://chat.whatsapp.com/H27qlYbbIxHAiV9N8Vo5cu",
        "Enfermagem 2024:\nhttps://chat.whatsapp.com/CQ6HUhlOMBKCzorGI2IY6R",
        "Engenharia Civil:\nhttps://chat.whatsapp.com/HZcZYJAQZP8Av4EdVLF5Rn",
        "Engenharia de Produção:\nhttps://chat.whatsapp.com/E8M7yOgzEss0Bvog3XoBDg",
        "Engenharia de Software\nhttps://chat.whatsapp.com/Hi2gQENFx0JIxakkIndBdd",
        "Engenharia Mecânica:\nhttps://chat.whatsapp.com/IBiEPyDHu9uAK8Td2N9gKz",
        "Estética:\nhttps://chat.whatsapp.com/GpfHGUWpeh62wc8m4oqPnM",
        "Farmácia:\nhttps://chat.whatsapp.com/EDWHHFDP9qIGm02PeNwcIH",
        "Filosofia:\nhttps://chat.whatsapp.com/GEDuR9mRGUMBE6YtOdqwr4",
        "Fisioterapia:\nhttps://chat.whatsapp.com/IfJlgWYA0PB3trjupH294H",
        "Gastronomia:\nhttps://chat.whatsapp.com/HLcUA5ApntO2hYqxGEb79J",
        "Gerontologia\nhttps://chat.whatsapp.com/Jh9pfowiV1I299iAi9YKef",
        "Gestão Ambiental:\nhttps://chat.whatsapp.com/Lt83nBTczCSIUSvz8JPKA4",
        "Gestão Comercial:\nhttps://chat.whatsapp.com/L97a9uC2Wrr66hFL9goRjm",
        "Gestão da Qualidade:\n\nhttps://chat.whatsapp.com/Jh7FE2dJZeA6PauQjM17lI",
        "Gestão de Negócios Imobiliários:\nhttps://chat.whatsapp.com/ImZkFjJpqlY4b8v7t3Wulz",
        "Gestão de Saúde Pública\nhttps://chat.whatsapp.com/JEXq94tMgXz1NMsyoxLT8v",
        "Gestão de Segurança Privada:\nhttps://chat.whatsapp.com/BEBGB29iK9O0r3Ooywkedj",
        "Gestão de Segurança do Trabalho:\nhttps://chat.whatsapp.com/DZeZWEQCnRMAAS2PPOaNT1",
        "Gestão Financeira:\nhttps://chat.whatsapp.com/FDkL4brq3Gq5EqQCRXOLTT",
        "Gestão Hospitalar:\nhttps://chat.whatsapp.com/J6I2TRSJU0V5UeVPq3VH8b",
        "Gestão Pública:\nhttps://chat.whatsapp.com/CmSQwuQnJ6UAMthVd0B0U1",
        "Gestão de Tecnologia da Informação:\nhttps://chat.whatsapp.com/Hr9vjGlHQoeER94a7tdfmO",
        "Investigação Forense e Perícia Criminal:\nhttps://chat.whatsapp.com/EXNGbvIETksFzMfYkYls8X",
        "Jornalismo\nhttps://chat.whatsapp.com/GAOjpzG4rfkBxBDo3iAFb6",
        "Letras:\nhttps://chat.whatsapp.com/KR36F6nrbHJD9yDYZ0rHH2",
        "Letras - Libras:\nhttps://chat.whatsapp.com/DiwdKdsYWeyKzemxjawhqi",
        "Letras - Inglês/Português:\nhttps://chat.whatsapp.com/DJKBe7mulYbBam5aLgsmIj",
        "Licenciatura Geografia:\nhttps://chat.whatsapp.com/HqwyD2TU8SXGgxtxbmXC7u",
        "Licenciatura História:\nhttps://chat.whatsapp.com/HS2FrvY1FFTB8ibK4bY3Dw",
        "Licenciatura Matemática:\nhttps://chat.whatsapp.com/BVULFZ9gswVDRX4XtSjCKn",
        "Logística:\nhttps://chat.whatsapp.com/LkQjeXEzmVV7l6toKkDNvB",
        "Manutenção Industrial:\nhttps://chat.whatsapp.com/KnzRvSLttNyJdTi6Y0yW2X",
        "Marketing:\nhttps://chat.whatsapp.com/LHsIa1MdJxL3uXdvqbYtVT",
        "Matemática:\nhttps://chat.whatsapp.com/LO6ePG3QSFI6YxH2Fxc89p",
        "Nutrição:\nhttps://chat.whatsapp.com/DEUSRaVYhCB412lGdr8BuY",
        "Pedagogia 2023:\nhttps://chat.whatsapp.com/LJ64EfaFoyBD16iEkvrT4F",
        "Pedagogia 2024:\nhttps://chat.whatsapp.com/BEhZLoEDQ7k6nEl4AEDlEf",
        "Podologia:\nhttps://chat.whatsapp.com/JbTsSKKJCUD8F1oIGEpMgH",
        "Processos Gerenciais:\nhttps://chat.whatsapp.com/HMod92FeAGu3S3cywDBi8v",
        "PsicoPedagogia\nhttps://chat.whatsapp.com/DgAkgRdemVZCXSmjWgNzrU",
        "Publicidade e Propaganda:\nhttps://chat.whatsapp.com/CoO4XWiK0Q8CsyiLhFdZDM",
        "Química:\nhttps://chat.whatsapp.com/CqOQmCYJ6hkH939mYTbeQL",
        "Radiologia:\nhttps://chat.whatsapp.com/FWqI2XAUfZdH4dbjcnluZ7",
        "Recursos Humanos:\nhttps://chat.whatsapp.com/CXLEvJikg7QLPxjnzQeRiF",
        "Secretariado:\nhttps://chat.whatsapp.com/J2ZqVboLWLdCyL9Yl11Fyh",
        "Serviço Social:\nhttps://chat.whatsapp.com/Hb6hbFpaXNpBiB8ncHQL7j",
        "Serviços Jurídicos e Notariais\nhttps://chat.whatsapp.com/Ffr0b5UJ5uxBSHVoj11EBa",
        "Sistemas de Internet/Análise e Desenvolvimento de Sistemas:\nhttps://chat.whatsapp.com/GUYQnmVjrBH4iMIeoxhztr",
        "Teatro:\nhttps://chat.whatsapp.com/Kcgti6JUvZy21Mz1PsQEI3",
        "Teologia:\nhttps://chat.whatsapp.com/FKG0e0awwBh6youv6DnzlI",
        "Terapia Ocupacional:\nhttps://chat.whatsapp.com/Cpv44FIaR0TBP84ZOVOKA1",
        "Terapias Integrativas e Complementares:\nhttps://chat.whatsapp.com/DJ7CThqHKaE9eusOzqpW9B",
        "Tecnologia da Informação:\nhttps://chat.whatsapp.com/Hr9vjGlHQoeER94a7tdfmO",
        "GRUPO\nSEMANA DE CONHECIMENTOS GERAIS: \nhttps://chat.whatsapp.com/Do5c18oqR1M0PrsOF8Vkyf",
        "GRUPO\nPROJETO DE EXTENSÃO\nhttps://chat.whatsapp.com/DPguoKPxxjJ28wj2tNhNFn",
        "GRUPO GESTÃO FINANCEIRA\nhttps://chat.whatsapp.com/DugurSYhlv85AvOAk64jt1",
        "Quem aqui faz\n PEDAGOGIA?",
        "Quem aqui faz\n EDUCAÇÃO FÍSICA?",
        "Quem aqui faz\n ENFERMAGEM?",
        "Quem aqui faz\n BIOMEDICINA?",
        "Quem aqui faz\n ADMINISTRAÇÃO?",
        "Quem aqui faz\n LICENCIATURA?",
        "Quem aqui faz\n GASTRONOMIA?",
        "Quem aqui faz\n RECURSOS HUMANOS?",
        "Quem aqui faz\n GESTÃO DE SAÚDE PÚBLICA?",
        "Quem aqui faz\n CIÊNCIAS CONTÁBEIS?",
        "Quem aqui faz\n DESIGN DE INTERIORES?",
        "Quem aqui faz\n ARQUITERURA?",
        "Quem aqui faz\n Engenharia?",
        "Quem aqui faz\n FARMÁRCIA?",
        "Quem aqui faz\n GESTÃO FINANCEIRA?",
        "Quem aqui faz\n TECNOLOGIA DA INFORMAÇÃO?",
        "Quem aqui faz\n LETRAS?",
        "Quem aqui faz\n MARKETING?",
        "Quem aqui é da área de \n TI?",
        "Quem aqui faz\n RECURSOS HUMANOS?",
        "Quem aqui é da área de \n TI?",
        "Quem aqui faz\n SERVIÇO SOCIAL?",
        "SUAS ATIVIDADES ESTÃO EM DIA?",
        "JÁ ESTUDOU UM POUCO HOJE?",
        "Qual sua dica para quem está iniciando no EAD",
        "Qual sua maior dificuldade no STUDEO",
        "Faltam muitas horas para completar suas horas de Extensão?",
        "Faltam muitas horas para completar suas horas de ATIVIDADES COMPLEMENTARES?",
        "Você prefere livro físico ou apenas o digital?",
        "Você sabia que a Unicesumar fornece o pacote Office gratuitamente? Já pediu o seu?",
        "Qual é o seu horário preferido de estudar?",
        "Quem toma café para estudar levanta a mão!!",
        "Quem tem filho, trabalha e ainda tem tempo de estudar, levanta mão junto comigo!!!",
        "Você sabia que as Atividade da SEMANA DE CONHECIMENTOS GERAIS valem 1 ponto em todas as disciplinas? É muita coisa gente!!!",
        "Já fez seu PROJETO DE ENSINO deste módulo?",
        "Na sua cidade hoje está frio ou calor?",
        "Você prefere estudar no frio ou no calor?",
        "Vamos nos Apresentar!! Diga seu curso e onde é seu polo!",
        "O que você está achando da UNICESUMAR?",
        "Voltei a estudar depois de muito tempo parado. Mais alguém?",
        "Se um amigo te pergunta uma DICA para fazer o MAPA, qual você daria?",
        "Precisa de algum grupo de estudos na Unicesumar?",
        "Precisam de algum grupo?",
        "Falta muito para você se formar?", 
        "A persistência é o caminho do êxito. Vamos começar a semana com foco nos nossos objetivos!",
        "Cada pequeno progresso é um passo mais perto do sucesso. Não desista!",
        "Lembre-se: grandes realizações requerem tempo e paciência. Continue se esforçando!",
        "Sonhe grande e trabalhe duro. Sua dedicação será recompensada!",
        "Acorde cada dia com a determinação de se superar. Você é capaz de mais do que imagina!",
        "Você sabia? A Unicesumar está entre as melhores universidades privadas do Brasil!",
        "Dica acadêmica: Aproveite os recursos da biblioteca online para complementar seus estudos.",
        "Novidade no campus: Confira os novos cursos disponíveis este semestre na Unicesumar.",
        "A Unicesumar orgulha-se de sua comunidade estudantil diversificada. Conheça mais sobre nossos programas de intercâmbio.",
        "Fique atento aos prazos de inscrições para as atividades extracurriculares deste ano!",
        "Qual foi o professor que mais influenciou sua jornada acadêmica até agora? Compartilhe sua história!",
        "Quais são suas técnicas de estudo preferidas durante as provas finais?",
        "O que você espera alcançar ao fim do seu curso? Compartilhe seus objetivos profissionais!",
        "Como você equilibra estudo e lazer? Dicas são sempre bem-vindas!",
        "Qual foi o maior desafio que você enfrentou na universidade e como superou?",
        "Estudar em grupo pode aumentar a retenção de conhecimento. Já tentou?",
        "Dica de ouro: Faça pausas regulares para manter sua mente afiada durante longas sessões de estudo.",
        "Experimente métodos de estudo diferentes, como mapas mentais ou flashcards, para descobrir o que funciona melhor para você.",
        "Mantenha seu ambiente de estudo organizado. Um espaço limpo pode melhorar sua concentração.",
        "Não subestime o poder de uma boa noite de sono antes de um dia de provas!",
        "Equilibrar trabalho e estudos pode ser desafiador. Como você administra seu tempo eficientemente?",
        "Saúde mental é crucial. Quais atividades ajudam você a relaxar após uma semana de estudos intensos?",
        "Compartilhe uma foto de seu local de estudo! Vamos ver quem tem o espaço mais inspirador.",
        "Qual foi a última vez que você fez algo pela primeira vez? Talvez seja hora de experimentar algo novo!",
        "Como você se mantém motivado quando os estudos ficam intensos?",
        "Quem mais está ansioso pelas próximas férias? Como planejam usar esse tempo livre?",
        "Vamos começar um desafio! Poste uma foto da sua estação de estudos e marque um amigo para fazer o mesmo!",
        "Como você mantém a motivação em disciplinas que são mais desafiadoras para você?",
        "Se você pudesse estudar qualquer coisa por um dia, o que seria? Compartilhe suas paixões ocultas!",
        "Dicas para novos alunos: O que você gostaria de saber quando começou a estudar na Unicesumar?",
        "Quais aplicativos ou ferramentas online você recomendaria para ajudar nos estudos? Compartilhem suas descobertas!",
        "Como você se prepara para uma apresentação ou seminário importante?",
        "Qual é o seu lugar favorito no campus para relaxar ou estudar? Compartilhe suas dicas secretas!",
        "Desafio da semana: compartilhe uma vitória pessoal ou acadêmica que você teve recentemente!",
        "O que te inspira a continuar quando os estudos ficam pesados?",
        "Quem é seu maior apoio na universidade? Faça uma homenagem a essa pessoa aqui no grupo!",
        "Que música não pode faltar na sua playlist de estudos? Compartilhe suas melhores faixas!",
        "Qual é a matéria que você mais gosta? E por quê?",
        "Como você lida com o stress das semanas de prova? Compartilhe suas estratégias!",
        "Se você tivesse a oportunidade de mudar algo na Unicesumar, o que seria?",
        "Uma citação que define sua jornada acadêmica até agora. Qual é a sua?",
        "Qual foi o projeto ou trabalho que mais te desafiou na universidade? Como você o superou?",
        "Dicas para economizar tempo: quais são seus hacks de produtividade favoritos?",
        "Que conselho você daria para alguém que está apenas começando sua jornada acadêmica?",
        "Quais são seus objetivos acadêmicos e pessoais para este semestre?",
        "Qual foi a coisa mais interessante que você aprendeu na última semana?",
        "Estudos à noite ou pela manhã? Qual é o seu horário preferido e por quê?",
        "Quais desafios você enfrentou ao adaptar-se ao ensino online, se houve?",
        "Como você usa a tecnologia para melhorar seus estudos?",
        "O que você faz para garantir que está cuidando de sua saúde mental e física durante o período letivo?",
        "Vamos começar a semana com foco nos estudos! Qual é sua maior meta acadêmica este semestre?",
        "Já deu uma olhada nos eventos online da Unicesumar esta semana? Não perca!",
        "Bom dia, comunidade! Que disciplina está te desafiando mais atualmente?",
        "Hora do café e de uma pausa nos estudos! O que você faz para relaxar entre as sessões de estudo?",
        "Dica do dia: Organize seu espaço de estudo para melhorar sua produtividade. Alguém tem mais alguma dica?",
        "Uma citação para inspirar: 'O sucesso é a soma de pequenos esforços, repetidos dia após dia.' - Robert Collier",
        "Como você equilibra estudo e lazer? Compartilhe suas estratégias!",
        "Qual é a sua motivação para estudar hoje?",
        "Desafio do dia: Compartilhe uma foto do seu local de estudos!",
        "Estudar em grupo ou sozinho? Qual é o seu estilo preferido e por quê?",
        "Lembre-se: cada página lida hoje te aproxima mais do seu diploma!",
        "Participe do nosso questionário da semana: Qual recurso da Unicesumar você mais valoriza? Vote abaixo!",
        "Fim de semana chegando... Já planejou seus estudos para aproveitar o tempo livre?",
        "Dica de saúde: Não esqueça de beber água e se alongar entre as horas de estudo!",
        "Quem aqui já começou a preparação para as provas finais? ",
        "Flashback Friday: Compartilhe uma conquista sua deste semestre que te deixou orgulhoso!",
        "Qual ferramenta online da Unicesumar tem ajudado mais nos seus estudos? ",
        "Segunda-feira: nova semana, novas oportunidades de aprendizado. Vamos nessa!",
        "Você sabia? A Unicesumar oferece diversos cursos extracurriculares gratuitos. Aproveite!",
        "Hora da pausa: qual é o seu snack favorito durante os estudos?",
        "Todo esforço conta! Compartilhe uma pequena vitória de hoje.",
        "Que tal começarmos um clube do livro virtual da Unicesumar? Quem apoia, diz 'eu'!",
        "Precisando de motivação? Lembre-se por que começou. Mantenha o foco!",
        "Dica cultural: Explore os recursos da biblioteca online da Unicesumar.",
        "Quarta de bem-estar: como você cuida da sua saúde mental durante o semestre?",
        "Enquete: Vocês preferem aulas online ou presenciais? Comentem suas opiniões!",
        "Alguém tem dicas para lidar com o nervosismo antes das apresentações?",
        "Hoje é um ótimo dia para agradecer um professor. Vamos mostrar nossa gratidão!",
        "Final do dia, hora do check-in: você cumpriu suas metas de estudo hoje?",
        "Deus, cuida de cada dia desta semana, aumenta minha fé, renova as minhas forças, ajuda-me a vencer as dificuldades de cada dia, livra-me das palavras de maldições, das palavras que ferem, do olho que inveja, livra-me do laço do inimigo, tira da minha frente tudo aquilo que quer me destruir, guia-me pelo caminho da verdade, me abençoe, abençoe minha familia e amigos. Cuida de mim Senhor. Amém!",
        "Essas atividades de extensão estão me fazendo tirar o foco das disciplinas do módulo.   Será que só eu me sinto assim... quais atividades mais fáceis vocês indicam?"


        ]

    elif faculdade == "UNOPAR":

        lista = [
        "ADMINISTRAÇÃO\nhttps://chat.whatsapp.com/DrTM5BmeyZNIDcfeFB2wb9",
        "CIÊNCIAS BIOLÓGICAS - 1º ANO (1° e 2º SEMESTRE)\nhttps://chat.whatsapp.com/ISxIC2OfiQCFMagmAPq11C",
        "CIÊNCIAS CONTÁBEIS (1° e 2º SEMESTRE)\nhttps://chat.whatsapp.com/GKo8PPudiyV13wMgefe8lN",
        "EDUCAÇÃO FÍSICA\nhttps://chat.whatsapp.com/Lmyrp7UDBrYHIftDdxILXv",
        "ENFERMAGEM\nhttps://chat.whatsapp.com/FqmXRFO51no9VvsDuvmEiv",
        "GESTÃO PÚBLICA\nhttps://chat.whatsapp.com/DHpnmFBDvOQH6DdJyM9mHw",
        "PEDAGOGIA - 1º ANO (1° e 2º SEMESTRE)\nhttps://chat.whatsapp.com/K7zyaY2qol5KBadDCAApZK",
        "PEDAGOGIA - 2º ANO (3° e 4º SEMESTRE)\nhttps://chat.whatsapp.com/GEcRnhy0mC2FBvNdecesDP",
        "PEDAGOGIA - 3º ANO (5° e 6º SEMESTRE)\nhttps://chat.whatsapp.com/JyidGEcxxNq8JyxOsS7qM2",
        "PEDAGOGIA - 4º ANO (7° e 8º SEMESTRE)\nhttps://chat.whatsapp.com/F3jVIzBU63KEhBpYqr4LoY",
        "MARKETING - 1º ANO (1° e 2º SEMESTRE)\nhttps://chat.whatsapp.com/EdVlbUxX3Nd3B82NIxzdRz",
        "NUTRIÇÃO - 1º ANO (1° e 2º SEMESTRE)\nhttps://chat.whatsapp.com/DRzYvgpk45NHXqikpjUglF",
        "SERVIÇO SOCIAL\nhttps://chat.whatsapp.com/J7NJRnbDIBhG7ihrgJgE3m" ,
        "LETRAS PORTUGUÊS\nhttps://chat.whatsapp.com/FlDY4aBI0AVEvlQxORJC51",
        "GESTÃO AMBIENTAL\nhttps://chat.whatsapp.com/GeURZ0e1vFpAENfLVNRCt7",
        "PROCESSOS GERENCIAIS\nhttps://chat.whatsapp.com/E8q9yjtxdlbC04C31QB6EI",
        "RECURSOS HUMANOS\nhttps://chat.whatsapp.com/IxzN2jtckF34BAldTQ07Od",
        "HISTÓRIA\nhttps://chat.whatsapp.com/EaValYfQWO86KWsPKWoe29",
        "Quem aqui faz\n PEDAGOGIA?",
        "Quem aqui faz\n EDUCAÇÃO FÍSICA?",
        "Quem aqui faz\n ENFERMAGEM?",
        "Quem aqui faz\n BIOMEDICINA?",
        "Quem aqui faz\n ADMINISTRAÇÃO?",
        "Quem aqui faz\n LICENCIATURA?",
        "Quem aqui faz\n GASTRONOMIA?",
        "Quem aqui faz\n RECURSOS HUMANOS?",
        "Quem aqui faz\n GESTÃO DE SAÚDE PÚBLICA?",
        "Quem aqui faz\n CIÊNCIAS CONTÁBEIS?",
        "Quem aqui faz\n DESIGN DE INTERIORES?",
        "Quem aqui faz\n ARQUITERURA?",
        "Quem aqui faz\n Engenharia?",
        "Quem aqui faz\n FARMÁRCIA?",
        "Quem aqui faz\n GESTÃO FINANCEIRA?",
        "Quem aqui faz\n TECNOLOGIA DA INFORMAÇÃO?",
        "Quem aqui faz\n LETRAS?",
        "Quem aqui faz\n MARKETING?",
        "Quem aqui é da área de \n TI?",
        "Quem aqui faz\n SERVIÇO SOCIAL?",
        "SUAS ATIVIDADES ESTÃO EM DIA?",
        "JÁ ESTUDOU UM POUCO HOJE?",
        "Qual sua dica para quem está iniciando no EAD",
        "Qual sua maior dificuldade no STUDEO",
        "Faltam muitas horas para completar suas horas de ATIVIDADES COMPLEMENTARES?",
        "Você prefere livro físico ou apenas o digital?",
        "A Unopar fornece o pacote Office gratuitamente?",
        "Qual é o seu horário preferido de estudar?",
        "Quem toma café para estudar levanta a mão!!",
        "Quem tem filho, trabalha e ainda tem tempo de estudar, levanta mão junto comigo!!!",
        "Na sua cidade hoje está frio ou calor?",
        "Você prefere estudar no frio ou no calor?",
        "Vamos nos Apresentar!! Diga seu curso e onde é seu polo!",
        "O que você está achando da UNOPAR?",
        "Voltei a estudar depois de muito tempo parado. Mais alguém?",  
        "Se um amigo te pergunta uma DICA para fazer o PORTFÓLIO, qual você daria?" ,
        "Precisa de algum grupo de estudos na Unopar?",
        "Precisam de algum grupo?",
        "Falta muito para você se formar?",    
        "A persistência é o caminho do êxito. Vamos começar a semana com foco nos nossos objetivos!",
        "Cada pequeno progresso é um passo mais perto do sucesso. Não desista!",
        "Lembre-se: grandes realizações requerem tempo e paciência. Continue se esforçando!",
        "Sonhe grande e trabalhe duro. Sua dedicação será recompensada!",
        "Acorde cada dia com a determinação de se superar. Você é capaz de mais do que imagina!",
        "Você sabia? A Unicesumar está entre as melhores universidades privadas do Brasil!",
        "Dica acadêmica: Aproveite os recursos da biblioteca online para complementar seus estudos.",
        "Novidade no campus: Confira os novos cursos disponíveis este semestre na Unicesumar.",
        "A Unicesumar orgulha-se de sua comunidade estudantil diversificada. Conheça mais sobre nossos programas de intercâmbio.",
        "Fique atento aos prazos de inscrições para as atividades extracurriculares deste ano!",
        "Qual foi o professor que mais influenciou sua jornada acadêmica até agora? Compartilhe sua história!",
        "Quais são suas técnicas de estudo preferidas durante as provas finais?",
        "O que você espera alcançar ao fim do seu curso? Compartilhe seus objetivos profissionais!",
        "Como você equilibra estudo e lazer? Dicas são sempre bem-vindas!",
        "Qual foi o maior desafio que você enfrentou na universidade e como superou?",
        "Estudar em grupo pode aumentar a retenção de conhecimento. Já tentou?",
        "Dica de ouro: Faça pausas regulares para manter sua mente afiada durante longas sessões de estudo.",
        "Experimente métodos de estudo diferentes, como mapas mentais ou flashcards, para descobrir o que funciona melhor para você.",
        "Mantenha seu ambiente de estudo organizado. Um espaço limpo pode melhorar sua concentração.",
        "Não subestime o poder de uma boa noite de sono antes de um dia de provas!",
        "Equilibrar trabalho e estudos pode ser desafiador. Como você administra seu tempo eficientemente?",
        "Saúde mental é crucial. Quais atividades ajudam você a relaxar após uma semana de estudos intensos?",
        "Compartilhe uma foto de seu local de estudo! Vamos ver quem tem o espaço mais inspirador.",
        "Qual foi a última vez que você fez algo pela primeira vez? Talvez seja hora de experimentar algo novo!",
        "Como você se mantém motivado quando os estudos ficam intensos?",
        "Quem mais está ansioso pelas próximas férias? Como planejam usar esse tempo livre?",
        "Vamos começar um desafio! Poste uma foto da sua estação de estudos e marque um amigo para fazer o mesmo!",
        "Como você mantém a motivação em disciplinas que são mais desafiadoras para você?",
        "Se você pudesse estudar qualquer coisa por um dia, o que seria? Compartilhe suas paixões ocultas!",
        "Dicas para novos alunos: O que você gostaria de saber quando começou a estudar na Unicesumar?",
        "Quais aplicativos ou ferramentas online você recomendaria para ajudar nos estudos? Compartilhem suas descobertas!",
        "Como você se prepara para uma apresentação ou seminário importante?",
        "Qual é o seu lugar favorito no campus para relaxar ou estudar? Compartilhe suas dicas secretas!",
        "Desafio da semana: compartilhe uma vitória pessoal ou acadêmica que você teve recentemente!",
        "O que te inspira a continuar quando os estudos ficam pesados?",
        "Quem é seu maior apoio na universidade? Faça uma homenagem a essa pessoa aqui no grupo!",
        "Que música não pode faltar na sua playlist de estudos? Compartilhe suas melhores faixas!",
        "Qual é a matéria que você mais gosta? E por quê?",
        "Como você lida com o stress das semanas de prova? Compartilhe suas estratégias!",
        "Se você tivesse a oportunidade de mudar algo na Unicesumar, o que seria?",
        "Uma citação que define sua jornada acadêmica até agora. Qual é a sua?",
        "Qual foi o projeto ou trabalho que mais te desafiou na universidade? Como você o superou?",
        "Dicas para economizar tempo: quais são seus hacks de produtividade favoritos?",
        "Que conselho você daria para alguém que está apenas começando sua jornada acadêmica?",
        "Quais são seus objetivos acadêmicos e pessoais para este semestre?",
        "Qual foi a coisa mais interessante que você aprendeu na última semana?",
        "Estudos à noite ou pela manhã? Qual é o seu horário preferido e por quê?",
        "Quais desafios você enfrentou ao adaptar-se ao ensino online, se houve?",
        "Como você usa a tecnologia para melhorar seus estudos?",
        "O que você faz para garantir que está cuidando de sua saúde mental e física durante o período letivo?",
        "Já deu uma olhada nos eventos online da Unopar esta semana? Não perca!",
        "Bom dia, comunidade! Que disciplina está te desafiando mais atualmente?",
        "Hora do café e de uma pausa nos estudos! O que você faz para relaxar entre as sessões de estudo?",
        "Dica do dia: Organize seu espaço de estudo para melhorar sua produtividade. Alguém tem mais alguma dica?",
        "Uma citação para inspirar: 'O sucesso é a soma de pequenos esforços, repetidos dia após dia.' - Robert Collier",
        "Como você equilibra estudo e lazer? Compartilhe suas estratégias!",
        "Qual é a sua motivação para estudar hoje?",
        "Desafio do dia: Compartilhe uma foto do seu local de estudos!",
        "Estudar em grupo ou sozinho? Qual é o seu estilo preferido e por quê?",
        "Lembre-se: cada página lida hoje te aproxima mais do seu diploma!",
        "Participe do nosso questionário da semana: Qual recurso da Unopar você mais valoriza? Vote abaixo!",
        "Fim de semana chegando... Já planejou seus estudos para aproveitar o tempo livre?",
        "Dica de saúde: Não esqueça de beber água e se alongar entre as horas de estudo!",
        "Quem aqui já começou a preparação para as provas finais? ",
        "Flashback Friday: Compartilhe uma conquista sua deste semestre que te deixou orgulhoso!",
        "Qual ferramenta online da Unopar tem ajudado mais nos seus estudos? ",
        "Segunda-feira: nova semana, novas oportunidades de aprendizado. Vamos nessa!",
        "Você sabia? A Unopar oferece diversos cursos extracurriculares gratuitos. Aproveite!",
        "Hora da pausa: qual é o seu snack favorito durante os estudos?",
        "Todo esforço conta! Compartilhe uma pequena vitória de hoje.",
        "Que tal começarmos um clube do livro virtual da Unopar? Quem apoia, diz 'eu'!",
        "Precisando de motivação? Lembre-se por que começou. Mantenha o foco!",
        "Dica cultural: Explore os recursos da biblioteca online da Unopar.",
        "Quarta de bem-estar: como você cuida da sua saúde mental durante o semestre?",
        "Enquete: Vocês preferem aulas online ou presenciais? Comentem suas opiniões!",
        "Alguém tem dicas para lidar com o nervosismo antes das apresentações?",
        "Hoje é um ótimo dia para agradecer um professor. Vamos mostrar nossa gratidão!",
        "Final do dia, hora do check-in: você cumpriu suas metas de estudo hoje?",
        "Deus, cuida de cada dia desta semana, aumenta minha fé, renova as minhas forças, ajuda-me a vencer as dificuldades de cada dia, livra-me das palavras de maldições, das palavras que ferem, do olho que inveja, livra-me do laço do inimigo, tira da minha frente tudo aquilo que quer me destruir, guia-me pelo caminho da verdade, me abençoe, abençoe minha familia e amigos. Cuida de mim Senhor. Amém!" 
        ]

    elif faculdade == "UNICSUL":
    
        lista = [
        "GRUPO NO WHATSAPP PARA DISCUTIR ATIVIDADES DA UNICSUL\nhttps://chat.whatsapp.com/HSpMDReHBF49qNBQrxwUwV"
        "Quem aqui faz\n PEDAGOGIA?",
        "Quem aqui faz\n EDUCAÇÃO FÍSICA?",
        "Quem aqui faz\n ENFERMAGEM?",
        "Quem aqui faz\n BIOMEDICINA?",
        "Quem aqui faz\n ADMINISTRAÇÃO?",
        "Quem aqui faz\n LICENCIATURA?",
        "Quem aqui faz\n GASTRONOMIA?",
        "Quem aqui faz\n RECURSOS HUMANOS?",
        "Quem aqui faz\n GESTÃO DE SAÚDE PÚBLICA?",
        "Quem aqui faz\n CIÊNCIAS CONTÁBEIS?",
        "Quem aqui faz\n DESIGN DE INTERIORES?",
        "Quem aqui faz\n ARQUITERURA?",
        "Quem aqui faz\n Engenharia?",
        "Quem aqui faz\n FARMÁRCIA?",
        "Quem aqui faz\n GESTÃO FINANCEIRA?",
        "Quem aqui faz\n TECNOLOGIA DA INFORMAÇÃO?",
        "Quem aqui faz\n LETRAS?",
        "Quem aqui faz\n MARKETING?",
        "Quem aqui é da área de \n TI?",
        "Quem aqui faz\n SERVIÇO SOCIAL?",
        "SUAS ATIVIDADES ESTÃO EM DIA?",
        "JÁ ESTUDOU UM POUCO HOJE?",
        "Qual sua dica para quem está iniciando no EAD",
        "Qual sua maior dificuldade no STUDEO",
        "Faltam muitas horas para completar suas horas de ATIVIDADES COMPLEMENTARES?",
        "Você prefere livro físico ou apenas o digital?",
        "A UnicSul fornece o pacote Office gratuitamente?",
        "Qual é o seu horário preferido de estudar?",
        "Quem toma café para estudar levanta a mão!!",
        "Quem tem filho, trabalha e ainda tem tempo de estudar, levanta mão junto comigo!!!",
        "Na sua cidade hoje está frio ou calor?",
        "Você prefere estudar no frio ou no calor?",
        "Vamos nos Apresentar!! Diga seu curso e onde é seu polo!",
        "O que você está achando da UnicSul?",
        "Voltei a estudar depois de muito tempo parado. Mais alguém?",  
        "Se um amigo te pergunta uma DICA para fazer o PORTFÓLIO, qual você daria?" ,
        "Precisa de algum grupo de estudos na UnicSul?",
        "Precisam de algum grupo?",
        "Falta muito para você se formar?",    
        "A persistência é o caminho do êxito. Vamos começar a semana com foco nos nossos objetivos!",
        "Cada pequeno progresso é um passo mais perto do sucesso. Não desista!",
        "Lembre-se: grandes realizações requerem tempo e paciência. Continue se esforçando!",
        "Sonhe grande e trabalhe duro. Sua dedicação será recompensada!",
        "Acorde cada dia com a determinação de se superar. Você é capaz de mais do que imagina!",
        "Você sabia? A Unicesumar está entre as melhores universidades privadas do Brasil!",
        "Dica acadêmica: Aproveite os recursos da biblioteca online para complementar seus estudos.",
        "Novidade no campus: Confira os novos cursos disponíveis este semestre na Unicesumar.",
        "A Unicesumar orgulha-se de sua comunidade estudantil diversificada. Conheça mais sobre nossos programas de intercâmbio.",
        "Fique atento aos prazos de inscrições para as atividades extracurriculares deste ano!",
        "Qual foi o professor que mais influenciou sua jornada acadêmica até agora? Compartilhe sua história!",
        "Quais são suas técnicas de estudo preferidas durante as provas finais?",
        "O que você espera alcançar ao fim do seu curso? Compartilhe seus objetivos profissionais!",
        "Como você equilibra estudo e lazer? Dicas são sempre bem-vindas!",
        "Qual foi o maior desafio que você enfrentou na universidade e como superou?",
        "Estudar em grupo pode aumentar a retenção de conhecimento. Já tentou?",
        "Dica de ouro: Faça pausas regulares para manter sua mente afiada durante longas sessões de estudo.",
        "Experimente métodos de estudo diferentes, como mapas mentais ou flashcards, para descobrir o que funciona melhor para você.",
        "Mantenha seu ambiente de estudo organizado. Um espaço limpo pode melhorar sua concentração.",
        "Não subestime o poder de uma boa noite de sono antes de um dia de provas!",
        "Equilibrar trabalho e estudos pode ser desafiador. Como você administra seu tempo eficientemente?",
        "Saúde mental é crucial. Quais atividades ajudam você a relaxar após uma semana de estudos intensos?",
        "Compartilhe uma foto de seu local de estudo! Vamos ver quem tem o espaço mais inspirador.",
        "Qual foi a última vez que você fez algo pela primeira vez? Talvez seja hora de experimentar algo novo!",
        "Como você se mantém motivado quando os estudos ficam intensos?",
        "Quem mais está ansioso pelas próximas férias? Como planejam usar esse tempo livre?",
        "Vamos começar um desafio! Poste uma foto da sua estação de estudos e marque um amigo para fazer o mesmo!",
        "Como você mantém a motivação em disciplinas que são mais desafiadoras para você?",
        "Se você pudesse estudar qualquer coisa por um dia, o que seria? Compartilhe suas paixões ocultas!",
        "Dicas para novos alunos: O que você gostaria de saber quando começou a estudar na Unicesumar?",
        "Quais aplicativos ou ferramentas online você recomendaria para ajudar nos estudos? Compartilhem suas descobertas!",
        "Como você se prepara para uma apresentação ou seminário importante?",
        "Qual é o seu lugar favorito no campus para relaxar ou estudar? Compartilhe suas dicas secretas!",
        "Desafio da semana: compartilhe uma vitória pessoal ou acadêmica que você teve recentemente!",
        "O que te inspira a continuar quando os estudos ficam pesados?",
        "Quem é seu maior apoio na universidade? Faça uma homenagem a essa pessoa aqui no grupo!",
        "Que música não pode faltar na sua playlist de estudos? Compartilhe suas melhores faixas!",
        "Qual é a matéria que você mais gosta? E por quê?",
        "Como você lida com o stress das semanas de prova? Compartilhe suas estratégias!",
        "Se você tivesse a oportunidade de mudar algo na Unicesumar, o que seria?",
        "Uma citação que define sua jornada acadêmica até agora. Qual é a sua?",
        "Qual foi o projeto ou trabalho que mais te desafiou na universidade? Como você o superou?",
        "Dicas para economizar tempo: quais são seus hacks de produtividade favoritos?",
        "Que conselho você daria para alguém que está apenas começando sua jornada acadêmica?",
        "Quais são seus objetivos acadêmicos e pessoais para este semestre?",
        "Qual foi a coisa mais interessante que você aprendeu na última semana?",
        "Estudos à noite ou pela manhã? Qual é o seu horário preferido e por quê?",
        "Quais desafios você enfrentou ao adaptar-se ao ensino online, se houve?",
        "Como você usa a tecnologia para melhorar seus estudos?",
        "O que você faz para garantir que está cuidando de sua saúde mental e física durante o período letivo?",
        "Já deu uma olhada nos eventos online da UnicSul esta semana? Não perca!",
        "Bom dia, comunidade! Que disciplina está te desafiando mais atualmente?",
        "Hora do café e de uma pausa nos estudos! O que você faz para relaxar entre as sessões de estudo?",
        "Dica do dia: Organize seu espaço de estudo para melhorar sua produtividade. Alguém tem mais alguma dica?",
        "Uma citação para inspirar: 'O sucesso é a soma de pequenos esforços, repetidos dia após dia.' - Robert Collier",
        "Como você equilibra estudo e lazer? Compartilhe suas estratégias!",
        "Qual é a sua motivação para estudar hoje?",
        "Desafio do dia: Compartilhe uma foto do seu local de estudos!",
        "Estudar em grupo ou sozinho? Qual é o seu estilo preferido e por quê?",
        "Lembre-se: cada página lida hoje te aproxima mais do seu diploma!",
        "Participe do nosso questionário da semana: Qual recurso da UnicSul você mais valoriza? Vote abaixo!",
        "Fim de semana chegando... Já planejou seus estudos para aproveitar o tempo livre?",
        "Dica de saúde: Não esqueça de beber água e se alongar entre as horas de estudo!",
        "Quem aqui já começou a preparação para as provas finais? ",
        "Flashback Friday: Compartilhe uma conquista sua deste semestre que te deixou orgulhoso!",
        "Qual ferramenta online da UnicSul tem ajudado mais nos seus estudos? ",
        "Segunda-feira: nova semana, novas oportunidades de aprendizado. Vamos nessa!",
        "Você sabia? A UnicSul oferece diversos cursos extracurriculares gratuitos. Aproveite!",
        "Hora da pausa: qual é o seu snack favorito durante os estudos?",
        "Todo esforço conta! Compartilhe uma pequena vitória de hoje.",
        "Que tal começarmos um clube do livro virtual da UnicSul? Quem apoia, diz 'eu'!",
        "Precisando de motivação? Lembre-se por que começou. Mantenha o foco!",
        "Dica cultural: Explore os recursos da biblioteca online da UnicSul.",
        "Quarta de bem-estar: como você cuida da sua saúde mental durante o semestre?",
        "Enquete: Vocês preferem aulas online ou presenciais? Comentem suas opiniões!",
        "Alguém tem dicas para lidar com o nervosismo antes das apresentações?",
        "Hoje é um ótimo dia para agradecer um professor. Vamos mostrar nossa gratidão!",
        "Final do dia, hora do check-in: você cumpriu suas metas de estudo hoje?",
        "Deus, cuida de cada dia desta semana, aumenta minha fé, renova as minhas forças, ajuda-me a vencer as dificuldades de cada dia, livra-me das palavras de maldições, das palavras que ferem, do olho que inveja, livra-me do laço do inimigo, tira da minha frente tudo aquilo que quer me destruir, guia-me pelo caminho da verdade, me abençoe, abençoe minha familia e amigos. Cuida de mim Senhor. Amém!"

        ]
    
    else:
        
        lista = [
        "Quem aqui faz\n PEDAGOGIA?",
        "Quem aqui faz\n EDUCAÇÃO FÍSICA?",
        "Quem aqui faz\n ENFERMAGEM?",
        "Quem aqui faz\n BIOMEDICINA?",
        "Quem aqui faz\n ADMINISTRAÇÃO?",
        "Quem aqui faz\n LICENCIATURA?",
        "Quem aqui faz\n GASTRONOMIA?",
        "Quem aqui faz\n RECURSOS HUMANOS?",
        "Quem aqui faz\n GESTÃO DE SAÚDE PÚBLICA?",
        "Quem aqui faz\n CIÊNCIAS CONTÁBEIS?",
        "Quem aqui faz\n DESIGN DE INTERIORES?",
        "Quem aqui faz\n ARQUITERURA?",
        "Quem aqui faz\n Engenharia?",
        "Quem aqui faz\n FARMÁRCIA?",
        "Quem aqui faz\n GESTÃO FINANCEIRA?",
        "Quem aqui faz\n TECNOLOGIA DA INFORMAÇÃO?",
        "Quem aqui faz\n LETRAS?",
        "Quem aqui faz\n MARKETING?",
        "Quem aqui é da área de \n TI?",
        "Quem aqui faz\n SERVIÇO SOCIAL?",
        "SUAS ATIVIDADES ESTÃO EM DIA?",
        "JÁ ESTUDOU UM POUCO HOJE?",
        "Qual sua dica para quem está iniciando no EAD",
        "Qual sua maior dificuldade no STUDEO",
        "Faltam muitas horas para completar suas horas de ATIVIDADES COMPLEMENTARES?",
        "Você prefere livro físico ou apenas o digital?",
        "A UnicSul fornece o pacote Office gratuitamente?",
        "Qual é o seu horário preferido de estudar?",
        "Quem toma café para estudar levanta a mão!!",
        "Quem tem filho, trabalha e ainda tem tempo de estudar, levanta mão junto comigo!!!",
        "Na sua cidade hoje está frio ou calor?",
        "Você prefere estudar no frio ou no calor?",
        "Vamos nos Apresentar!! Diga seu curso e onde é seu polo!",
        "O que você está achando da UnicSul?",
        "Voltei a estudar depois de muito tempo parado. Mais alguém?",  
        "Se um amigo te pergunta uma DICA para fazer o PORTFÓLIO, qual você daria?" ,
        "Precisa de algum grupo de estudos na UnicSul?",
        "Precisam de algum grupo?",
        "Falta muito para você se formar?",    
        "A persistência é o caminho do êxito. Vamos começar a semana com foco nos nossos objetivos!",
        "Cada pequeno progresso é um passo mais perto do sucesso. Não desista!",
        "Lembre-se: grandes realizações requerem tempo e paciência. Continue se esforçando!",
        "Sonhe grande e trabalhe duro. Sua dedicação será recompensada!",
        "Acorde cada dia com a determinação de se superar. Você é capaz de mais do que imagina!",
        "Você sabia? A Unicesumar está entre as melhores universidades privadas do Brasil!",
        "Dica acadêmica: Aproveite os recursos da biblioteca online para complementar seus estudos.",
        "Novidade no campus: Confira os novos cursos disponíveis este semestre na Unicesumar.",
        "A Unicesumar orgulha-se de sua comunidade estudantil diversificada. Conheça mais sobre nossos programas de intercâmbio.",
        "Fique atento aos prazos de inscrições para as atividades extracurriculares deste ano!",
        "Qual foi o professor que mais influenciou sua jornada acadêmica até agora? Compartilhe sua história!",
        "Quais são suas técnicas de estudo preferidas durante as provas finais?",
        "O que você espera alcançar ao fim do seu curso? Compartilhe seus objetivos profissionais!",
        "Como você equilibra estudo e lazer? Dicas são sempre bem-vindas!",
        "Qual foi o maior desafio que você enfrentou na universidade e como superou?",
        "Estudar em grupo pode aumentar a retenção de conhecimento. Já tentou?",
        "Dica de ouro: Faça pausas regulares para manter sua mente afiada durante longas sessões de estudo.",
        "Experimente métodos de estudo diferentes, como mapas mentais ou flashcards, para descobrir o que funciona melhor para você.",
        "Mantenha seu ambiente de estudo organizado. Um espaço limpo pode melhorar sua concentração.",
        "Não subestime o poder de uma boa noite de sono antes de um dia de provas!",
        "Equilibrar trabalho e estudos pode ser desafiador. Como você administra seu tempo eficientemente?",
        "Saúde mental é crucial. Quais atividades ajudam você a relaxar após uma semana de estudos intensos?",
        "Compartilhe uma foto de seu local de estudo! Vamos ver quem tem o espaço mais inspirador.",
        "Qual foi a última vez que você fez algo pela primeira vez? Talvez seja hora de experimentar algo novo!",
        "Como você se mantém motivado quando os estudos ficam intensos?",
        "Quem mais está ansioso pelas próximas férias? Como planejam usar esse tempo livre?",
        "Vamos começar um desafio! Poste uma foto da sua estação de estudos e marque um amigo para fazer o mesmo!",
        "Como você mantém a motivação em disciplinas que são mais desafiadoras para você?",
        "Se você pudesse estudar qualquer coisa por um dia, o que seria? Compartilhe suas paixões ocultas!",
        "Dicas para novos alunos: O que você gostaria de saber quando começou a estudar na Unicesumar?",
        "Quais aplicativos ou ferramentas online você recomendaria para ajudar nos estudos? Compartilhem suas descobertas!",
        "Como você se prepara para uma apresentação ou seminário importante?",
        "Qual é o seu lugar favorito no campus para relaxar ou estudar? Compartilhe suas dicas secretas!",
        "Desafio da semana: compartilhe uma vitória pessoal ou acadêmica que você teve recentemente!",
        "O que te inspira a continuar quando os estudos ficam pesados?",
        "Quem é seu maior apoio na universidade? Faça uma homenagem a essa pessoa aqui no grupo!",
        "Que música não pode faltar na sua playlist de estudos? Compartilhe suas melhores faixas!",
        "Qual é a matéria que você mais gosta? E por quê?",
        "Como você lida com o stress das semanas de prova? Compartilhe suas estratégias!",
        "Se você tivesse a oportunidade de mudar algo na Unicesumar, o que seria?",
        "Uma citação que define sua jornada acadêmica até agora. Qual é a sua?",
        "Qual foi o projeto ou trabalho que mais te desafiou na universidade? Como você o superou?",
        "Dicas para economizar tempo: quais são seus hacks de produtividade favoritos?",
        "Que conselho você daria para alguém que está apenas começando sua jornada acadêmica?",
        "Quais são seus objetivos acadêmicos e pessoais para este semestre?",
        "Qual foi a coisa mais interessante que você aprendeu na última semana?",
        "Estudos à noite ou pela manhã? Qual é o seu horário preferido e por quê?",
        "Quais desafios você enfrentou ao adaptar-se ao ensino online, se houve?",
        "Como você usa a tecnologia para melhorar seus estudos?",
        "O que você faz para garantir que está cuidando de sua saúde mental e física durante o período letivo?",
        "Já deu uma olhada nos eventos online da UnicSul esta semana? Não perca!",
        "Bom dia, comunidade! Que disciplina está te desafiando mais atualmente?",
        "Hora do café e de uma pausa nos estudos! O que você faz para relaxar entre as sessões de estudo?",
        "Dica do dia: Organize seu espaço de estudo para melhorar sua produtividade. Alguém tem mais alguma dica?",
        "Uma citação para inspirar: 'O sucesso é a soma de pequenos esforços, repetidos dia após dia.' - Robert Collier",
        "Como você equilibra estudo e lazer? Compartilhe suas estratégias!",
        "Qual é a sua motivação para estudar hoje?",
        "Desafio do dia: Compartilhe uma foto do seu local de estudos!",
        "Estudar em grupo ou sozinho? Qual é o seu estilo preferido e por quê?",
        "Lembre-se: cada página lida hoje te aproxima mais do seu diploma!",
        "Participe do nosso questionário da semana: Qual recurso da UnicSul você mais valoriza? Vote abaixo!",
        "Fim de semana chegando... Já planejou seus estudos para aproveitar o tempo livre?",
        "Dica de saúde: Não esqueça de beber água e se alongar entre as horas de estudo!",
        "Quem aqui já começou a preparação para as provas finais? ",
        "Flashback Friday: Compartilhe uma conquista sua deste semestre que te deixou orgulhoso!",
        "Qual ferramenta online da UnicSul tem ajudado mais nos seus estudos? ",
        "Segunda-feira: nova semana, novas oportunidades de aprendizado. Vamos nessa!",
        "Você sabia? A UnicSul oferece diversos cursos extracurriculares gratuitos. Aproveite!",
        "Hora da pausa: qual é o seu snack favorito durante os estudos?",
        "Todo esforço conta! Compartilhe uma pequena vitória de hoje.",
        "Que tal começarmos um clube do livro virtual da UnicSul? Quem apoia, diz 'eu'!",
        "Precisando de motivação? Lembre-se por que começou. Mantenha o foco!",
        "Dica cultural: Explore os recursos da biblioteca online da UnicSul.",
        "Quarta de bem-estar: como você cuida da sua saúde mental durante o semestre?",
        "Enquete: Vocês preferem aulas online ou presenciais? Comentem suas opiniões!",
        "Alguém tem dicas para lidar com o nervosismo antes das apresentações?",
        "Hoje é um ótimo dia para agradecer um professor. Vamos mostrar nossa gratidão!",
        "Final do dia, hora do check-in: você cumpriu suas metas de estudo hoje?",
        "Deus, cuida de cada dia desta semana, aumenta minha fé, renova as minhas forças, ajuda-me a vencer as dificuldades de cada dia, livra-me das palavras de maldições, das palavras que ferem, do olho que inveja, livra-me do laço do inimigo, tira da minha frente tudo aquilo que quer me destruir, guia-me pelo caminho da verdade, me abençoe, abençoe minha familia e amigos. Cuida de mim Senhor. Amém!"
    ]
    link = random.choice(lista)

    return link
